In [1]:
import numpy as np

In [8]:
np.array([[1,2],[1,2]]).shape[0]

2

# 1. Writing a handwritten dot product

In [56]:
def dot(a: list, b:list):

    mat_a, mat_b = np.array(a), np.array(b)

    #only valid when ncol of a = nrow of b
    if mat_a.shape[-1]!=mat_b.shape[0]: 
        raise Exception('Invalid Matrix Dimensions')

    mat_ans = []
    nrows = mat_a.shape[0] #resulting rows
    ncols = mat_b.shape[1] #resulting cols
    for row in range(nrows): 
        ans_row = []
        for col in range(ncols):
            ele = 0
            for i in range(nrows): #dot product loop
                ele += mat_a[row, i]*mat_b[i, col]
            ans_row.append(ele)
        mat_ans.append(ans_row)
    
    return np.array(mat_ans)

In [61]:
print("Handwritten function:")
print(dot([[4,-3,-2], [6,0,-1], [2,1,3]], [[5, 4], [6, 7], [-4,-3]]))

print()
print("np.dot() method:")
print(np.dot([[4,-3,-2], [6,0,-1], [2,1,3]], [[5, 4], [6, 7], [-4,-3]]))

Handwritten function:
[[10  1]
 [34 27]
 [ 4  6]]

np.dot() method:
[[10  1]
 [34 27]
 [ 4  6]]


In [62]:
print("Handwritten function:")
print(dot([[1,0], [0,1]], [[1,2,3,4], [5,6,7,8]]))

print()
print("np.dot() method:")
print(np.dot([[1,0], [0,1]], [[1,2,3,4], [5,6,7,8]]))

Handwritten function:
[[1 2 3 4]
 [5 6 7 8]]

np.dot() method:
[[1 2 3 4]
 [5 6 7 8]]
